### PR TITLE
Added final sherlock audit to repo

### PR DESCRIPTION
**Pull request by ith-harvey**
self explanatory, added final Sherlock audit

### CODE REVIEW

**Review by MikeHathaway — APPROVED** [review]
LGTM - can you add these to the README as well?

**Review by EdNoepel — COMMENTED** [review]
Shouldn't the README be updated to link to this?

**Comment by ith-harvey** [comment]
> Shouldn't the README be updated to link to this?

updated -> https://github.com/ajna-finance/audits/pull/1/commits/78c5beaed8e6298d604859cbaa77a0ef60a9b850

**Comment by ith-harvey** [comment]
> LGTM - can you add these to the README as well?

updated -> https://github.com/ajna-finance/audits/pull/1/commits/78c5beaed8e6298d604859cbaa77a0ef60a9b850

**Review by EdNoepel — APPROVED** [review]
👌

**Pull request merged**
